### ISSUE TITLE
Atom freezes when editing a line with a slash and then 2 double quotes after it.

### ISSUE THREAD

**Issue by Stormageddon0** [JASONews/autocomplete-bash-builtins#1]
Atom freezes when editing a line with a slash and then 2 double quotes after it.

**Reproduction:**

**1.** disable all third-party packages in atom except autocomplete-bash-builtins.
**2.** open a new file insert "#! /bin/bash" on first line and save file.
**3.** type '/asdfjklasdfjklasdfjklasdfjkl" " '  (slash, about 30 random letters, double quote, double quote) on line 2 without single quotes.
**4.** insert a space or letter between between the double quotes.

This doesn't happen in safe mode.

**Expected behavior:**
* Atom doesn't freeze, further editing is seamless. Atom behaves normally.

**Actual behavior:**
* Atom freezes and if you wait long enough, atom will resume.
* Comment out line 2 with # and the behavior no longer happens until uncommented
* The longer the line in between the slash and the quotes, the longer the freeze will be.
* The slash does not have to be the first character on the line

**Software versions:**
* **Atom:**       1.14.2
* **Electron:** 1.3.13
* **OS:**         linux 4.8.0-39-generic
* **Misc**
    * apm  1.15.3
    * npm  3.10.5
    * node 4.4.5 x64
    * python 2.7.12+
    * git 2.9.3

If you can't reproduce the error, just let me know!

EDIT: Altered title and first line of issue to be more discriptive.

**Comment by JASONews** [comment]
Hi @joshwiker14 ! Thank you for reporting this bug. Yes, I can reproduce it on my laptop by following your steps. Gonna fix it!  : )

**Comment by Stormageddon0** [comment]
Thank you so much! I can confirm that the fix solves the issue for me!

**Comment by JASONews** [comment]
@joshwiker14  No problem! Thank you!  : )
